/ext3/miniconda3/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 201, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 55, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/scratch/cg3306/climate/CM2P6Param/saves/snapshots/lsrp.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run/snapshot.py", line 223, in <module>
    main()
  File "run/snapshot.py", line 210, in main
    lsrp_evs.to_netcdf(fileame,mode = 'w')
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/core/dataset.py", line 1882, in to_netcdf
    return to_netcdf(  # type: ignore  # mypy cannot resolve the overloads:(
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/api.py", line 1193, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 384, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 332, in __init__
    self.format = self.ds.data_model
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 393, in ds
    return self._acquire()
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/netCDF4_.py", line 387, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "/ext3/miniconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 189, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "/ext3/miniconda3/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 207, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'/scratch/cg3306/climate/CM2P6Param/saves/snapshots/lsrp.nc'
